# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77551f27e918538bdef2c73f0459fc54a8ce5d3c1b2bbe4f9b676d4c3677c667ff3077b49bc683aee60dcaa5c5a36a0e8c6dbb43f2a76012e9431f11223af121

test:
  secret_key_base: 4f0534a60bd08161192b7eaa135b7207bc799ef6792d22b9608703ef050021b5ad3885e201607a3785454be56f8f5671ad89deafb8b9d1bcc0d5c1acff320454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
